### ISSUE TITLE
W+ enum leads to sdk creation problems

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#383]
#### Describe the bug

The enum w+ in the openapi/swagger specs lead to problems since clients are generated with stripping the `+` which leads to double constants (W).

```
            access:
              description: Access level.
              type: string
              default: rw
              enum:
                - rw
                - w
                - m
                - w+
```

```
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;

	ignoring go.mod;

	see 'go help modules'

github.com/gyselroth/balloon-sdk-go/models

# github.com/gyselroth/balloon-sdk-go/models

models/core_v2_acl_rule.go:83:2: CoreV2ACLRulePrivilegeW redeclared in this block

	previous declaration at models/core_v2_acl_rule.go:77:35
```

The same applies to openapi-codegen for the php sdk.

#### Expected behavior
Rename the enum to "rp" (read plus => read/write owned files, no access to non owned).
**Attention**: This changes requires a migration since all access rules use "w+" and also requires minimal changes in the access control (rename const).

#### Environment
 - balloon server version: v2.6.5
