### ISSUE TITLE
Job Balloon\Async\CleanTrash ends with an error

### ISSUE THREAD

**Issue by rootinier** [gyselroth/balloon#463]
#### Describe the bug
Call to a member function getId() on null on file /usr/share/balloon/src/lib/Filesystem/Node/Collection.php line 808

#### To Reproduce
Activate job Balloon\Async\CleanTrash, config:
```
Balloon\Hook\CleanTrash:
          arguments:
            config:
              interval: 28800
              max_age: 2592000
```

#### Expected behavior
Empty the trash completely

#### Environment
 - balloon server version: v2.7.4
